### ISSUE TITLE
Support overriding output directory

### ISSUE THREAD

**Issue by sovanyio** [wcm-io-frontend/aem-clientlib-generator#12]
Currently the output is made as a subfolder in the working directory named after the client library name which makes for odd folder organization if the working directory was already organized as a client library ;). This additionally has the effect of enforcing an opinionated path to the resulting client library, which should be able to be overridden. 

I think it makes more sense to enable an output directory per-library, which for the purposes of the above usage would result in only generating the `.content.xml` and `{asset}.txt` files in the working directory, along with supporting the existing 'copy to output' in another directory such as `dist`.

**Comment by stefanseifert** [comment]
i think i makes sense to support this by adding a new configuration parameter (but keeping the current behavior as default behavior in place).

can you come up with a PR for this?

**Comment by stefanseifert** [comment]
thanks for the PR, we'll have a look into it!
