### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by sovanyio** [wcm-io-frontend/aem-clientlib-generator#17]
Currently this repository is using specific calls to `path.posix...`. I'm curious why this was done, as it breaks the ability to build the same repo on a posix AND a win system.

I've created a PR for this where my branch uses the typical path commands that vary by platform. Thoughts?

https://github.com/wcm-io-frontend/aem-clientlib-generator/pull/16

**Comment by ifahrentholz** [comment]
I'll investigate shortly why `posix` was used in the first place. 
If it's save to remove we'll merge your pull request.

**Comment by ifahrentholz** [comment]
Hi @sovanyio, 
we've tested you contribution in pull request #16 and our tests are failing on windows machines (see comment of @stefanseifert in your pull request). 

The posix variabel was introduced to fix issues with relative path under windows and it appears that we still need the posix property.

**Comment by ifahrentholz** [comment]
Closed since we have breaking tests. See closing comment in #16.
