### ISSUE TITLE
Add ability to wipe clientlib-target folder before copying over the clientlibs

### ISSUE THREAD

**Issue by henrykuijpers** [wcm-io-frontend/aem-clientlib-generator#19]
It would be nice if we're able to wipe the target folder before copying over the generated clientlibs.

We faced some issues with renaming/moving files and then the new files being merged in (leaving old, not overwritten files, to remain next to the actual correct files).

**Comment by stefanseifert** [comment]
this is already happening afaik.
can you give examples (or a demo project) where the cleaning of the `clientLibRoot` target folder is not working?

**Comment by henrykuijpers** [comment]
We were already thinking of something related to (filesystem) permissions, but didn't have time yet to verify that. I indeed see that the step is in place, but could it be that it's ignored when deleting failed? Instead of failing the build?

**Comment by mvegacr** [comment]
Hi!

I am seeing the same issue. After some runs it keeps all the old files without cleaning the folder. Here there is an screenshot of what I'm seeing.

<img width="211" alt="Screen Shot 2019-10-15 at 8 41 12 AM" src="https://user-images.githubusercontent.com/1007515/66832346-ba4ecc00-ef27-11e9-8a39-8f8b8b577ff4.png">

The js.txt is being generated with the latest one, so the reference is correct:

```
#base=js
2.46482714.chunk.js
main.900d15e9.chunk.js
runtime-main.5c03b920.js
```

**Comment by ifahrentholz** [comment]
Since the aem-clientlib-generator is not bundling any files I do think that the issue is caused by your build step. Please verify that your build (for example via webpack) correctly wipes all obsolete chunks.

**Comment by ifahrentholz** [comment]
Closed due to stale discussion.
