### ISSUE TITLE
Is it possible to have different clientlib root for each clientlib...am planning to have clientlibs at component level

### ISSUE THREAD

**Issue by Allan9217** [wcm-io-frontend/aem-clientlib-generator#24]

**Comment by ifahrentholz** [comment]
Hi @Allan9217,
I do think this is already possible. You can set the "**_path_**" property as documented in the README.md. 

> path {String} Clientlib root path (optional if options.clientLibRoot is set)

Therefore an configuration like this would lead to a clientlib package with a custom root:

```
module.exports = {
    context: __dirname,
    libs: [
        {
            name: "test.base.apps.fourthWithOutputPath",
            path: 'result/clientlibs-custom-root',
            assets: {
                js: {
                  ...
                },
                css: {
                  ...
                },
            }
        },
    ]
};
```

Please let me know if that solution is feasible for you or if there is something missing.

**Comment by Allan9217** [comment]
Hi @ifahrentholz,
Its working fine...Thanks 👍

**Comment by ifahrentholz** [comment]
Nice :)
