### ISSUE TITLE
Allow 'replaces' property

### ISSUE THREAD

**Issue by johanruttens** [wcm-io-frontend/aem-clientlib-generator#28]
I would like to make use of the 'replaces' property on the ClientLib.

Can this be allowed in `var clientLibDirectoryFields = ["embed", "dependencies", "cssProcessor", "jsProcessor", "allowProxy", "longCacheKey"];`

Thank you.

**Comment by johanruttens** [comment]
I have opened a pull request for this change.

Thank you

**Comment by stefanseifert** [comment]
i've added a comment to #29 - `disableIfReplacing` should than added as well

**Comment by johanruttens** [comment]
I've added an update to the PR; `disableIfReplacing` is now added
