### ISSUE TITLE
Missing property.

### ISSUE THREAD

**Issue by Agatta** [wcm-io-frontend/aem-clientlib-generator#35]
We needed to add yet another property in clientlib - 'guideComponentType' for our project. 
It's mising in clientLibDirectoryFields array. Wouldn't be better to turn all these properties to fully configurable list than hardcode them?

**Comment by ifahrentholz** [comment]
Thx for your contribution. The PR is merged and released with version **1.7.6**.
I tend to agree with you it would probably make sense to make these props configurable - maybe having some sensible defaults.
