### ISSUE TITLE
.content.xml file is not auto-generated with the clientlib

### ISSUE THREAD

**Issue by ahmed-musallam** [wcm-io-frontend/aem-clientlib-generator#4]
This is more of a question and potentially an enhancement. the `.content.xml` file that defines the clientlib's: node type, dependencies, embed, ...etc is not auto generated. Instead, a JSON file with all that information is generated. The VaultFile tool cannot convert JSON to node properties, also the AEM package manager cannot do so, it only supports XML as far as I know. Do you deploy AEM packages differently? or do you add your `.content.xml` seperately? if the latter, I'm considering making a PR to add XML support, thoughts?

**Comment by deveth0** [comment]
Hi @ahmed-musallam, 
if you deploy the clientlibs as a bundle instead of a content-package as shown in [wcm-io sample](https://github.com/wcm-io/wcm-io-samples/tree/develop/bundles/clientlibs) there is no need for the xml file :)

**Comment by ahmed-musallam** [comment]
@deveth0 Sorry for the late reply, this is fantastic!!, I was looking around and found this [sling doc](https://sling.apache.org/documentation/bundles/content-loading-jcr-contentloader.html
) I did not even know existed! I will use that.

But irrespective of this cool find, I think it would be valuable, for those who want to go the package-manager/FileVault route, to generate a `.content.xml` you already have everything in place, just add an option to generate xml instead of JSON in the clientlib. Is this something you would merge if I make a PR for ?

**Comment by matti142** [comment]
Somebody implemented your requested feature here https://github.com/kriden/aem-clientlib-generator/blob/master/index.js 
But he/she never created a pull request, so I don't know if it works.
Keep in mind, that a new feature also needs some test cases.

**Comment by ahmed-musallam** [comment]
@matti142 nice! thank you for sharing that! It would be nice to see it in the new version of the generator :)

**Comment by stefanseifert** [comment]
+1 for adding support for FileVault project layout as well to the aem-clientlib-generator. should be a configurable switch to generate either the json file, or the `.content.xml` file.

**Comment by didymu5** [comment]
Hi, just circling back to this conversation. Is there any plan to integrate the .context.xml option into this project? It might be good to add it as an additional flag of some sorts.

**Comment by didymu5** [comment]
did this happen yet?

**Comment by stefanseifert** [comment]
not yet - patches welcome!

**Comment by stefanseifert** [comment]
should be solved with #10 in the next release
