### ISSUE TITLE
Breaking change after bumping yargs

### ISSUE THREAD

**Issue by CezCz** [wcm-io-frontend/aem-clientlib-generator#40]
Yargs 17.0.1 requires Node 12 as per:
https://github.com/yargs/yargs/blob/master/package.json#L114

When bumping the lib here, we should also bump required node version here:
https://github.com/wcm-io-frontend/aem-clientlib-generator/blob/master/package.json#L36
And if we follow semantic release, that should be a major release as it is a breaking change.

**Comment by vladbailescu** [comment]
@ifahrentholz , this seems to have been caused by https://github.com/wcm-io-frontend/aem-clientlib-generator/commit/7247c0163f42dd6c9cd702d368cfa92175afc295, could that be reverted and a new release pushed?

**Comment by ifahrentholz** [comment]
Hi @CezCz, Hi @vladbailescu, 
I've released the new Version 1.7.7 and used yargs v16.2.0. This should fix the problem.
