### ISSUE TITLE
High severity issues

### ISSUE THREAD

**Issue by lbineau** [wcm-io-frontend/aem-clientlib-generator#44]
Dear developers,

I'd like to report a security issue with version 1.7.7 due to the usage of "a vulnerable version of **async** dependency".
<img width="894" alt="image" src="https://user-images.githubusercontent.com/1534688/166461181-a0b4096e-ec53-48b3-abf1-e1a540504254.png">

`npm audit fix --force` would actually downgrade to version 1.4.1 which is not a good solution I believe.

Could you do another release upgrading the vulnerable dependencies?

Thank you.

**Comment by ifahrentholz** [comment]
Hi @lbineau,
thx for your issue. I will update the dependency shortly.

**Comment by ifahrentholz** [comment]
The issue should be fixed with release v1.8.0
https://www.npmjs.com/package/aem-clientlib-generator

Regards
